CREATE TABLE USUARIO (
    CODIGUSU INT AUTO_INCREMENT NOT NULL,
    EMAIL VARCHAR (30),
    NOME VARCHAR (30),
    SENHA VARCHAR (30),
    PRIMARY KEY (CODIGUSU)
);
CREATE TABLE SETOR (
    CODIGUSU INT NOT NULL, -- Chave estrangeira para USUARIO
    NOME_SETOR VARCHAR(50),
    PRIMARY KEY (CODIGUSU),
    FOREIGN KEY (CODIGUSU) REFERENCES USUARIO(CODIGUSU)
);

-- Tabela para usuário do tipo DOCENTE
CREATE TABLE DOCENTE (
    CODIGUSU INT NOT NULL, -- Chave estrangeira para USUARIO
    CIDADE VARCHAR(50),
    CPF VARCHAR(14),
    DATA_NASCIMENTO DATE,
    PRIMARY KEY (CODIGUSU),
    FOREIGN KEY (CODIGUSU) REFERENCES USUARIO(CODIGUSU)
);
CREATE TABLE TURMA (
    CODTURMA INT PRIMARY KEY,
    ANO_INGRESSO INT,
    NUMERO INT,
    ANO INT,
    ANO_DE_OFERTA INT
);
CREATE TABLE CURSO (
    CODCURSO INT PRIMARY KEY,
    NOME VARCHAR(100),
    ANOS INT,
    CARGA_HORARIA INT
);
CREATE TABLE DISCENTE (
    MATRICULA INT PRIMARY KEY,
    NOME VARCHAR(100),
    CIDADE VARCHAR(100),
    EMAIL VARCHAR(100),
    GENERO VARCHAR(10),
    DATA_NASCIMENTO DATE,
    OBSERVACAO TEXT
);
CREATE TABLE DISCIPLINA (
    CODDISCIPLINA INT PRIMARY KEY,
    NOME VARCHAR(50),
    OBSERVACAO TEXT
);
CREATE TABLE ADMINISTRADOR (
    CODADM INT PRIMARY KEY,
    CPF VARCHAR(14),
    SENHA VARCHAR(30)
);
CREATE TABLE DOCENTE_COORDENA_CURSO (
    CODIGUSU INT NOT NULL,
    CODCURSO INT NOT NULL,
    PRIMARY KEY (CODIGUSU, CODCURSO),
    FOREIGN KEY (CODIGUSU) REFERENCES DOCENTE(CODIGUSU),
    FOREIGN KEY (CODCURSO) REFERENCES CURSO(CODCURSO)
);
CREATE TABLE REGENTE_TURMA (
    CODUSU INT NOT NULL,
    CODTURMA INT NOT NULL,
    PRIMARY KEY (CODUSU, CODTURMA),
    FOREIGN KEY (CODUSU) REFERENCES DOCENTE(CODIGUSU),
    FOREIGN KEY (CODTURMA) REFERENCES TURMA(CODTURMA)
);
CREATE TABLE CURSO_TURMA (
    CODCURSO INT NOT NULL,
    CODTURMA INT NOT NULL,
    PRIMARY KEY (CODCURSO, CODTURMA),
    FOREIGN KEY (CODCURSO) REFERENCES CURSO(CODCURSO),
    FOREIGN KEY (CODTURMA) REFERENCES TURMA(CODTURMA)
);
CREATE TABLE HISTORICO (
    CODSEMESTRE INT,
    CODUSU INT, -- Alteração do nome da coluna
    CODDISCIPLINA INT,
    MATRICULA_DISCENTE INT,
    CODTURMA INT,
    PARCIAL DECIMAL(5, 2),
    NUM_FALTAS INT,
    EXAME DECIMAL(5, 2),
    PRIMARY KEY (CODSEMESTRE, CODUSU, CODDISCIPLINA, MATRICULA_DISCENTE, CODTURMA),
    FOREIGN KEY (CODUSU) REFERENCES DOCENTE(CODIGUSU), -- Corrigindo a referência à tabela DOCENTE
    FOREIGN KEY (CODDISCIPLINA) REFERENCES DISCIPLINA(CODDISCIPLINA),
    FOREIGN KEY (MATRICULA_DISCENTE) REFERENCES DISCENTE(MATRICULA),
    FOREIGN KEY (CODTURMA) REFERENCES TURMA(CODTURMA)
);


